<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

namespace local_siakad;

defined('MOODLE_INTERNAL') || die();

/**
 * Billing operations and the automatic exam access they unlock.
 *
 * A student becomes exam-eligible as soon as every bill for a period is settled.
 * Eligibility is granted by adding the student to the Prodi cohort generated by
 * local_pascaprodi, so the existing Cohort sync enrolment gives them access to
 * the programme's courses without any manual step.
 *
 * @package    local_siakad
 * @copyright  2026
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */
final class billing {
    /** Bill fully settled. */
    public const STATUS_PAID = 'paid';

    /** Bill still outstanding. */
    public const STATUS_UNPAID = 'unpaid';

    /**
     * Record a payment against one bill and refresh the student's exam access.
     *
     * @param int $tagihanid Bill ID.
     * @param float|null $amount Amount paid, or null to settle the outstanding balance.
     * @param int|null $paidat Payment timestamp, defaults to now.
     * @return \stdClass The updated bill.
     */
    public static function pay(int $tagihanid, ?float $amount = null, ?int $paidat = null): \stdClass {
        $DB = external_db::get();

        $bill = $DB->get_record('local_siakad_tagihan', ['id' => $tagihanid], '*', MUST_EXIST);
        $now = $paidat ?? time();

        $paidamount = (float) $bill->paidamount + ($amount ?? ((float) $bill->amount - (float) $bill->paidamount));
        $paidamount = max(0.0, $paidamount);
        $settled = $paidamount >= (float) $bill->amount;

        $bill->paidamount = $paidamount;
        $bill->status = $settled ? self::STATUS_PAID : self::STATUS_UNPAID;
        $bill->paidat = $settled ? $now : null;
        $bill->timemodified = time();
        $DB->update_record('local_siakad_tagihan', $bill);

        self::refresh_exam_access((int) $bill->mahasiswaid, (string) $bill->period);

        return $bill;
    }

    /**
     * Check whether every bill in a period is settled.
     *
     * A student with no bill at all for the period is not considered settled, so a
     * missing billing record never silently opens an exam.
     */
    public static function is_settled(int $mahasiswaid, string $period): bool {
        $DB = external_db::get();

        $period = trim($period);
        if ($mahasiswaid <= 0 || $period === '') {
            return false;
        }

        $bills = $DB->get_records('local_siakad_tagihan', [
            'mahasiswaid' => $mahasiswaid,
            'period' => $period,
        ]);
        if (!$bills) {
            return false;
        }

        foreach ($bills as $bill) {
            if ($bill->status !== self::STATUS_PAID || (float) $bill->paidamount < (float) $bill->amount) {
                return false;
            }
        }

        return true;
    }

    /**
     * Return the outstanding balance across a period.
     */
    public static function outstanding(int $mahasiswaid, string $period): float {
        $DB = external_db::get();

        $bills = $DB->get_records('local_siakad_tagihan', [
            'mahasiswaid' => $mahasiswaid,
            'period' => trim($period),
        ]);

        $total = 0.0;
        foreach ($bills as $bill) {
            $total += max(0.0, (float) $bill->amount - (float) $bill->paidamount);
        }

        return $total;
    }

    /**
     * Grant or revoke Prodi cohort membership based on the settled state.
     *
     * @return bool True when the student is currently exam-eligible.
     */
    public static function refresh_exam_access(int $mahasiswaid, string $period): bool {
        global $CFG, $DB;

        $siakaddb = external_db::get();

        $student = $siakaddb->get_record('local_siakad_mahasiswa', ['id' => $mahasiswaid]);
        if (!$student || $student->status !== 'active') {
            return false;
        }

        $moodleuserid = (int) $siakaddb->get_field('local_siakad_user', 'moodleuserid', [
            'id' => $student->siakaduserid,
            'active' => 1,
        ]);
        if ($moodleuserid <= 0) {
            // Nothing to enrol until the SIAKAD identity is linked to a Moodle account.
            return false;
        }

        $settled = self::is_settled($mahasiswaid, $period);
        $cohortid = self::get_prodi_cohort_id((int) $student->prodiid);
        if (!$cohortid) {
            return $settled;
        }

        require_once($CFG->dirroot . '/cohort/lib.php');

        $ismember = $DB->record_exists('cohort_members', [
            'cohortid' => $cohortid,
            'userid' => $moodleuserid,
        ]);

        if ($settled && !$ismember) {
            cohort_add_member($cohortid, $moodleuserid);
        } else if (!$settled && $ismember) {
            cohort_remove_member($cohortid, $moodleuserid);
        }

        return $settled;
    }

    /**
     * Re-evaluate every active student for one billing period.
     *
     * @return array{granted:int,revoked:int,skipped:int}
     */
    public static function refresh_all(string $period): array {
        $result = ['granted' => 0, 'revoked' => 0, 'skipped' => 0];
        $students = external_db::get()->get_records('local_siakad_mahasiswa', ['status' => 'active'], 'id ASC', 'id');

        foreach ($students as $student) {
            $before = self::has_cohort_membership((int) $student->id);
            $after = self::refresh_exam_access((int) $student->id, $period);

            if ($after && !$before) {
                $result['granted']++;
            } else if (!$after && $before) {
                $result['revoked']++;
            } else {
                $result['skipped']++;
            }
        }

        return $result;
    }

    /**
     * Return the local_pascaprodi student cohort backing a programme, or 0.
     *
     * @param int $prodiid local_siakad_prodi ID.
     */
    public static function get_prodi_cohort_id(int $prodiid): int {
        global $DB;

        $pascaprodiid = prodi_sync::get_pascaprodi_id($prodiid);
        if ($pascaprodiid <= 0) {
            return 0;
        }

        // Reuse the local_pascaprodi idnumber contract so both plugins agree on the cohort.
        $idnumber = class_exists('\\local_pascaprodi\\manager')
            ? \local_pascaprodi\manager::cohort_idnumber($pascaprodiid)
            : 'pasca:prodi:' . $pascaprodiid;

        $cohortid = $DB->get_field('cohort', 'id', ['idnumber' => $idnumber]);

        return $cohortid ? (int) $cohortid : 0;
    }

    /**
     * Whether the student currently sits in their Prodi cohort.
     */
    private static function has_cohort_membership(int $mahasiswaid): bool {
        global $DB;

        $siakaddb = external_db::get();

        $student = $siakaddb->get_record('local_siakad_mahasiswa', ['id' => $mahasiswaid], 'id,siakaduserid,prodiid');
        if (!$student) {
            return false;
        }

        $moodleuserid = (int) $siakaddb->get_field('local_siakad_user', 'moodleuserid', ['id' => $student->siakaduserid]);
        $cohortid = self::get_prodi_cohort_id((int) $student->prodiid);
        if ($moodleuserid <= 0 || $cohortid <= 0) {
            return false;
        }

        return $DB->record_exists('cohort_members', ['cohortid' => $cohortid, 'userid' => $moodleuserid]);
    }
}
